apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-config
  namespace: default
data:
  application.properties: |
    spring.main.allow-bean-definition-overriding=true
    hazelcast.config=classpath:hazelcast.xml
    server.port=8080
    logging.level.org.springframework=INFO
    logging.level.com.example.hazelcast=DEBUG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-cache-spring
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast-cache-spring
  template:
    metadata:
      labels:
        app: hazelcast-cache-spring
    spec:
      containers:
      - name: hazelcast-cache-spring
        image: hazelcast-cache-spring:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: hazelcast-config
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-cache-spring
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: hazelcast-cache-spring